### ISSUE TITLE
[1.15.2][3.3.8] Crash: IllegalAgumentException Null from BossArmorManager.getRandomSet

### ISSUE THREAD

**Issue by ChakatStormCloud** [Shadows-of-Fire/Apotheosis#293] opened 2021-01-09 11:43 UTC
Crash occurred during world creation on forge version 31.2.47 (most recent for 1.15.2)

Full Crashlog:
https://pastebin.com/Qs7Hu3h6

No idea what other mod might be causing this, or if it's a freak accident.

**Comment by ChakatStormCloud** [comment] 2021-01-09 13:50
After about 3 hours of testing, I've found the set of mods that cause this error.

crash here:
https://pastebin.com/4njSuL1z

Minestuck, JAOPCA, Create (version 2.4e specifically), and Apotheosis

if any of these are removed, the crash doesn't occur, pretty convoluted set of mods, (especially given the only reason to use create 2.4e is a random interaction mod that hasn't been updated yet) but it might also be caused in other scenarios, #265 seems to be similar.

**Comment by Shadows-of-Fire** [comment] 2021-01-20 01:30
duplicate of #265

**Closed as completed by Shadows-of-Fire** 2021-01-20 01:30 UTC
