### ISSUE TITLE
Helmet "+total attack damage" is not effective

### ISSUE THREAD

**Issue by rtxyd** [Shadows-of-Fire/Apotheosis#810] opened 2023-03-17 02:51 UTC
MCversion: 1.19.2
Placebo: 7.1.4
Apotheosis: 6.1.1
Test with dummmy, jei, apotheosis, when I set the gem with affix "+ x% total damage" to helmet , it seems not effective. The damage get no change.

**Comment by Shadows-of-Fire** [comment] 2023-03-17 02:54
What is the name of the gem?

**Comment by rtxyd** [comment] 2023-03-17 02:57
@Shadows-of-Fire Gem Of Warlord

**Comment by Shadows-of-Fire** [comment] 2023-03-17 05:48
Can't reproduce with the same setup in dev for 6.1.2, so what is most likely is it was side-effect fixed by the logic that fixed legacy gems.

**Closed as completed by Shadows-of-Fire** 2023-03-17 05:48 UTC
