### ISSUE TITLE
Error Relating to JEI Type Mods

### ISSUE THREAD

**Issue by TheUnnamedPlayerOfficial** [Shadows-of-Fire/Apotheosis#1244] opened 2024-05-13 21:02 UTC
Me and my friend Vinixatoki have created our own modpack and used this mod as an addition.
After playing for a bit, we encountered an error with the gems.

The gems collected from chests, IE generated structure, when put directly in inventory would be normal.  However, upon throwing the gem out of your inventory and picking it up again, the item comes back as an "Errored" gem, which has no use.  Gems that drop from mobs also fit this category.

Under strenuous testing, the error appears to happen to JustEnoughItems, or mods that show recipes and others, but also appears to be inconsistent as further testing brings successful results with no changes.  (I LOVE CODING YEAAAHHHH!)

If anything, I am not a coder and have no skill in this, and I would like to bring this up (As I saw someone else brought it up,) I did more searching and found what could be the cause.

Latest Mod Version 7.3.5
Game Version 1.20.1

**Comment by Shadows-of-Fire** [comment] 2024-05-13 21:23
This sounds like something is causing data loss on items, though I suspect that would propagate to more items than just Gems

**Comment by TheUnnamedPlayerOfficial** [comment] 2024-05-14 01:41
I would imagine, after some testing as well I found that it may have something to do with its configs as well, but its a very weird issue that seems to only be occuring in 1.20.1 versions.

**Comment by Shadows-of-Fire** [comment] 2024-05-21 07:43
duplicate of #1242

**Closed as completed by Shadows-of-Fire** 2024-05-21 07:43 UTC
