### ISSUE TITLE
Fletching Table Cannot be Used as Workstation

### ISSUE THREAD

**Issue by Sl1pstr3am** [Shadows-of-Fire/Apotheosis#309] opened 2021-01-29 21:29 UTC
After installing this mod, it seems that villagers can't use fletching tables as workstations. I'm not sure how you're doing the custom fletching table GUI's, but it seems to overwrite the workstation mechanic.

**Comment by Wheels35** [comment] 2021-02-03 05:15
I second this issue. I would love for this to be configurable in the village module as it stands right now disabling that module disables both the fletching and the wandering trader upgrade. That or fixing the underlying issue.

**Comment by Shadows-of-Fire** [comment] 2021-02-03 05:33
duplicate of #285

**Closed as completed by Shadows-of-Fire** 2021-02-03 05:33 UTC
