### ISSUE TITLE
Jade reports that I should report an error. Logs are not helping.

### ISSUE THREAD

**Issue by water-mizuu** [Shadows-of-Fire/Apotheosis#1126] opened 2024-01-07 16:44 UTC
Basically, Jade is showing this error on every block hovered.
This started happening when I disabled every module except the garden and spawner module.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/120231845/7fe16708-e9f2-4bf3-9eeb-51f3e8a6019f)

The logs of this run is 37k lines, so I doubt you want it. The (seemingly) relevant apotheosis logs are:

```
[00:32:06] [Worker-Main-15/INFO] [Jade/]: Start loading plugin at dev.shadowsoffire.apotheosis.spawn.compat.SpawnerHwylaPlugin
[00:32:06] [Worker-Main-15/INFO] [Jade/]: Start loading plugin at dev.shadowsoffire.apotheosis.ench.compat.EnchHwylaPlugin
[00:32:06] [Worker-Main-15/INFO] [Jade/]: Start loading plugin at dev.shadowsoffire.apotheosis.adventure.compat.AdventureHwylaPlugin
[00:33:19] [Render thread/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 2 calls to Enchantment#getMaxLevel() in net/minecraft/server/commands/EnchantCommand
[00:33:19] [Worker-Main-16/ERROR] [minecraft/TagLoader]: Couldn't load tag apotheosis:rarity_materials as it is missing following references: apotheosis:common_material (from Apotheosis-1.20.1-7.2.0.jar),
apotheosis:uncommon_material (from Apotheosis-1.20.1-7.2.0.jar),
apotheosis:rare_material (from Apotheosis-1.20.1-7.2.0.jar),
apotheosis:epic_material (from Apotheosis-1.20.1-7.2.0.jar),
apotheosis:mythic_material (from Apotheosis-1.20.1-7.2.0.jar),
apotheosis:ancient_material (from Apotheosis-1.20.1-7.2.0.jar)

...

[00:35:18] [Render thread/ERROR] [Jade/]: Caught unhandled exception : [dev.shadowsoffire.apotheosis.ench.compat.EnchHwylaPlugin@3316681e] java.lang.ExceptionInInitializerError
```

**Comment by jlp1528** [comment] 2024-01-08 02:37
Dupe of #1120

**Closed as completed** 2024-01-10 20:29 UTC
Labels: bug
