### ISSUE TITLE
No drops from mined blocks with apotheosis

### ISSUE THREAD

**Issue by Esseit** [Shadows-of-Fire/Apotheosis#516] opened 2022-01-24 00:16 UTC
[crash-2022-01-23_18.36.16-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7921777/crash-2022-01-23_18.36.16-server.txt)
I cannot get any block to drop when mined while the mod is installed. This is most likely due to some kind of mod conflict, but figured it was important to report this any way just incase. Crash happens after mining anywhere between 5 - blocks, regardless of how long you have been in the world itself. Crash log has been attached.

**Comment by Shadows-of-Fire** [comment] 2022-01-24 00:17
Duplicate of #514

**Closed as completed by Shadows-of-Fire** 2022-01-24 00:17 UTC
