### ISSUE TITLE
1.19.2  Error loading registry data

### ISSUE THREAD

**Issue by GreenForzeGaming** [Shadows-of-Fire/Apotheosis#754] opened 2023-01-01 21:19 UTC
Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / forge:biome_modifier_serializers]: apotheosis:blacklist

**Comment by GreenForzeGaming** [comment] 2023-01-01 21:26
well i went into the jar file and deleted the 6 boss dungeon json files, this fixed the problem.
something goes wrong when disabeling the adventure module and world gen for the boss dungeons

**Comment by Shadows-of-Fire** [comment] 2023-01-02 04:11
duplicate of #688

**Closed as completed by Shadows-of-Fire** 2023-01-02 04:11 UTC
