### ISSUE TITLE
Hard incompatibility with Block Armor mod and Garden module

### ISSUE THREAD

**Issue by jtgibson01** [Shadows-of-Fire/Apotheosis#80] opened 2019-08-19 10:41 UTC
Out of the two mods, Apotheosis remains the preferred mod for me, but there is a hard incompatibility between [Block Armor](https://github.com/2piradians/Block-Armor) and Apotheosis.

[crash-2019-08-19_03.07.18-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/3515390/crash-2019-08-19_03.07.18-client.txt)

Block Armor digs up textures from other mod data, but the Garden module of Apotheosis does not provide those textures in a fashion that Block Armor can read.  Bad Things ensue.

As implied by Furgle for other users' crashes, there is nothing that can be done on the Block Armor end.  Since the crash is technically Block Armor's functionality that is being impeded, however, the fix isn't really your fault: it can be as simple as adding a notification that Block Armor is incompatible, or as complex as resolving the bug.  Up to you!

Disabling the Garden module does allow Block Armor to work normally.  Obviously, this comes with the limitation of being unable to use the reed height and Ender Lead features.

**Comment by Shadows-of-Fire** [comment] 2019-08-19 13:55
The only fix for this is for BA to use IRegistryDelegate<Item> in place of Item for this list: https://github.com/2piradians/Block-Armor/blob/1.12.2/src/main/java/twopiradians/blockArmor/common/item/ArmorSet.java#L76
This is not an error caused by me, or resolvable by me, as BA is not respecting an existing forge feature (registry replacement).

**Closed by Shadows-of-Fire** 2019-08-19 13:55 UTC
