### ISSUE TITLE
Server sometimes crashes on startup

### ISSUE THREAD

**Issue by ViRb3** [Shadows-of-Fire/Apotheosis#256] opened 2020-11-24 00:09 UTC
This is a weird one, it doesn't always happen, usually we keep rebooting until it succeeds. Log: https://mcpaste.io/a72b1daffb01dd95

**Comment by grydian** [comment] 2020-11-29 19:43
I am getting this error everytime I try to load the server.  Any help would be greatly appreciated.

**Comment by Shadows-of-Fire** [comment] 2020-11-30 02:40
Duplicate of #255 (bug in psi, must be resolved by them)

**Closed as completed by Shadows-of-Fire** 2020-11-30 02:40 UTC
