### ISSUE TITLE
Data pack errors in 1.19.2

### ISSUE THREAD

**Issue by brasscrest** [Shadows-of-Fire/Apotheosis#691] opened 2022-10-25 10:05 UTC
Can't open a (single player) world, new or existing, in 1.19.2. Throws a data pack error. Checked with the following and no other mods:

Forge 43.1.47
Apotheosis 1.19.2-6.0.1
Placebo 1.19.2-7.0.1

https://pastebin.com/ruNG0Vuh

**Comment by Shadows-of-Fire** [comment] 2022-10-26 19:05
Duplicate of #688

**Closed as completed by Shadows-of-Fire** 2022-10-26 19:05 UTC
