### ISSUE TITLE
'apotheosis:superior_sigil_of_enhancement' crashes mc

### ISSUE THREAD

**Issue by arhp777** [Shadows-of-Fire/Apotheosis#830] opened 2023-03-28 13:29 UTC
[crash-2023-03-28_15.08.22-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11089875/crash-2023-03-28_15.08.22-client.txt)

**Comment by rtxyd** [comment] 2023-03-28 13:49
update your mod version,pls

**Comment by Shadows-of-Fire** [comment] 2023-03-30 20:47
duplicate of #813

**Closed as completed by Shadows-of-Fire** 2023-03-30 20:47 UTC
