### ISSUE TITLE
Fletching table cannot be used as jobsite when 'Village' module is enabled

### ISSUE THREAD

**Issue by plebble** [Shadows-of-Fire/Apotheosis#314] opened 2021-02-09 23:51 UTC
When the 'Village' module is enabled, villagers cannot use the fletching table to become a fletcher. I tested with other villager workstations and they got the profession immediately, but I could not get a villager to get the Fletcher profession. After disabling the Village module, the villager was able to get the Fletcher profession

**Comment by theboo** [comment] 2021-02-15 03:53
this is supposedly fixed in dev per https://github.com/Shadows-of-Fire/Apotheosis/issues/285... who knows when we will see it in an actual release.. Might be nice to get a hotfix out just for this as the fletcher villager is one of the most commonly used villagers for trading purposes.

**Comment by jmarakelian** [comment] 2021-02-17 05:15
Want to mention again, would love for this to be made an actual release. Currently playing ATM 6 hardcore and wanted some easy early game trading for emeralds, and this is a major annoyance. Even if ATM didn't update quickly, I could still update the mod locally and have it fixed

**Comment by Shadows-of-Fire** [comment] 2021-02-24 01:17
duplicate of #285

**Closed as completed by Shadows-of-Fire** 2021-02-24 01:17 UTC
