### ISSUE TITLE
Crash when upgrade affixes bow in anvil

### ISSUE THREAD

**Issue by Hurricaneforces** [Shadows-of-Fire/Apotheosis#394] opened 2021-06-01 02:20 UTC
Forge: 36.1.2
Apotheosis: Apotheosis-1.16.4-4.6.0

Upgrade Bow in Anvil. Put Bow in 1st slot then it will crash while put Affixes Tome in second slot
[crash-2021-06-01_09.13.00-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6572939/crash-2021-06-01_09.13.00-client.txt)

**Comment by Shadows-of-Fire** [comment] 2021-06-01 02:22
duplicate of #384

**Closed as completed by Shadows-of-Fire** 2021-06-01 02:22 UTC
