### ISSUE TITLE
[1.12.2] Duplicate key 9 Crash

### ISSUE THREAD

**Issue by hamsterpowerftw** [Shadows-of-Fire/Apotheosis#109] opened 2019-11-15 12:43 UTC
Crashes on new chunk gen, Both client and server are affected.
[Crash](https://paste.dimdev.org/ugevagezin.mccrash)

Also on a entirely different page, I love your work as a mod dev!

**Comment by Shadows-of-Fire** [comment] 2019-11-15 16:38
Duplicate of #108

**Closed by Shadows-of-Fire** 2019-11-15 16:38 UTC
