### ISSUE TITLE
[SEVERE] [CRASH] Crash on Disable Adventure Module

### ISSUE THREAD

**Issue by Camawama** [Shadows-of-Fire/Apotheosis#1049] opened 2023-10-22 02:25 UTC
Hello o/
I am testing out the Alpha Version (1.20.1) and found a pretty major bug. It took me quite some time to figure out exactly what was causing the crash too.

I disabled the Adventure, Potion, and Garden Module but now, when creating a new world, the game instantly crashes. It also causes big problems if I delete all worlds and attempt to click into singleplayer (since the world creation menu pops up and causes a crash).

Forge Version: **47.2.1**

Logs:
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13062232/latest.log)

Crash Report:
[crash-2023-10-21_21.21.01-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13062234/crash-2023-10-21_21.21.01-client.txt)

**Comment by Shadows-of-Fire** [comment] 2023-10-22 02:26
duplicate of #989

**Closed as not planned by Shadows-of-Fire** 2023-10-22 02:26 UTC

**Comment by Camawama** [comment] 2023-10-22 02:30
that was quick.
