### ISSUE TITLE
Crash with DynamicTrees

### ISSUE THREAD

**Issue by SSKirillSS** [Shadows-of-Fire/Apotheosis#15] opened 2019-03-08 21:07 UTC
Sorry for short description of the error.

The game crashes on startup when installing Apotheosis with DynamicTrees:
https://pastebin.com/hNcfzR4U

**Comment by Shadows-of-Fire** [comment] 2019-03-08 21:16
DynamicTrees/217

**Comment by SSKirillSS** [comment] 2019-03-29 06:35
The developer of Dynamic Trees is not particularly engaged in solving the problems of this mod. Apparently, I'll have to fix it myself. Sad :c

**Comment by edenhack** [comment] 2019-04-05 20:40
For whatever reason the garden module effects dynamic trees. If you really want both installed you can disable the garden module in apoth and DT will work alongside it.

**Comment by XvBUSHvX** [comment] 2019-05-02 07:18
Posting Here as the issue is still open and Dynamic Trees does work with Apotheosis and Placebo as long as Optifine isn't installed. 

Dynamic Trees Throws
"/ by 0" crash on startup w/ Dynamic Trees & Apotheosis/Placebo

> [Follow up.
> MC: 1.12.2
> Forge: 2836 (Issue encountered on an earlier version, but suggested by mod involved "Apotheosis"
> 
> Minimal list of mods to reproduce.
> 
> Dynamic Trees 0.9.5
> Apotheosis 1.9.4
> Placebo 1.6.0 (used by Apotheosis)
> Optifine: Encountered w/ "preview_OptiFine_1.12.2_HD_U_E4_pre4"
> Additionally tested against "OptiFine_1.12.2_HD_U_E3"
> 
> This was tested without VanillaFix for the same outcome, then VanillaFix was added for convenience with the hastebin (link) which replicates the above report.](https://github.com/ferreusveritas/DynamicTrees/issues/254#issuecomment-488570733)

**Comment by Shadows-of-Fire** [comment] 2019-05-02 07:22
I think I'll close this now.  There's literally nothing I can do about it on my end.  I don't even edit the texture for sugarcane, so it's really weird that it happens at all.

**Closed by Shadows-of-Fire** 2019-05-02 07:22 UTC
Labels: wontfix
