### ISSUE TITLE
Item stats displayed in the Apotheosis reforging table do not match the actual stats after reforging

### ISSUE THREAD

**Issue by GFoniX** [Shadows-of-Fire/Apotheosis#1156] opened 2024-02-09 08:04 UTC
Hello,

First of all, this is a duplicate of the following issue: https://github.com/AllTheMods/ATM-9/issues/413
However, it was posted on the ATM-9 issues sections instead of here. Since I noticed that there is no corresponding issue here, I am recreating a ticket.

Firstly, I am using version Apotheosis-1.20.1-7.2.2.jar.
When I use the reforging table to forge an item (usually in GOD tier), I end up with a version that is either worse or completely different from what was shown.
Could someone please help identify the problem?

**Comment by Shadows-of-Fire** [comment] 2024-02-09 08:07
Duplicate of #1145 
(fixed for next release)

**Closed as completed by Shadows-of-Fire** 2024-02-09 08:07 UTC
Labels: duplicate

**Comment by GFoniX** [comment] 2024-02-09 08:08
Sorry, I've didn't see the closed issues. Thanks
