### ISSUE TITLE
Affix errors when clicking start new world

### ISSUE THREAD

**Issue by wuzzard** [Shadows-of-Fire/Apotheosis#1319] opened 2024-08-13 23:37 UTC
I started a brand new instance (AT Launcher) and added ONLY Apotheosis and it's required dependencies. It throws a number of affix errors as noted in the quote below. This is triggered when I click on "Single Player" from the main menu (it also happens when I delete a world, or when I click "Create New World"). 

I have seen other similar issues listed, but not a bare-bones case. Is this expected?

Thanks

[latest.log](https://github.com/user-attachments/files/16606223/latest.log)

MC: 1.20.1
Forge: 47.3.5

Full Mod List:

- Apotheosis-1.20.1-7.4.0
- ApothicAttributes-1.20.1-1.3.6
- Patchouli-1.20.1-84-FORGE
- Placebo-1.20.1-8.6.2

Errors:
> [13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2
[13/08/2024 19:19:14 PM] [Render thread/ERROR] Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2

**Comment by Shadows-of-Fire** [comment] 2024-08-16 03:05
Duplicate of #1051

**Closed as completed by Shadows-of-Fire** 2024-08-16 03:05 UTC
