### ISSUE TITLE
Minecraft 1.20.1 Apotheosis causing mouseClicked event handler Crash, because of disabling Adventure module

### ISSUE THREAD

**Issue by purelytoucan** [Shadows-of-Fire/Apotheosis#1059] opened 2023-11-01 05:21 UTC
https://pastebin.com/isdbrz0a

The crash report

**Comment by Shadows-of-Fire** [comment] 2023-11-16 12:05
Duplicate of #989

**Closed as completed by Shadows-of-Fire** 2023-11-16 12:05 UTC
