### ISSUE TITLE
Infinite Duration Potion Effects Still Present 1.16.4

### ISSUE THREAD

**Issue by Danekjovax** [Shadows-of-Fire/Apotheosis#268] opened 2020-12-13 11:38 UTC
I saw a closed ticket to this issue, but as of this posting, it is still happening:
![image](https://user-images.githubusercontent.com/10191173/102010620-394aba80-3d0d-11eb-9683-3e81a325897d.png)
(excluding Night Vision)

MC 1.16.2
Forge 1.16.4-35.1.4
Apotheosis 1.16.3-4.4.1
Tombstone 6.0.2

Thank you.

**Comment by Beserkerlel** [comment] 2020-12-18 17:19
Having the same issue in the All The Mods 6 pack v1.3.5

I believe the instances I've found on my server come from Tombstone (Corail Tombstone) as they provide an enchant for weapons called Magic Syphon which can transfer positive effects back to the user.

#259 The dev addressed the issue there

**Comment by Danekjovax** [comment] 2020-12-18 17:42
Yes, it is Magic Siphon that is causing this.  Thanks for the link.  I'll review it and add what I have found, if helpful.

**Comment by Shadows-of-Fire** [comment] 2020-12-18 17:45
Duplicate of #259 (still weird there's no default time cap, but I suppose at least there's a config)

**Closed as completed by Shadows-of-Fire** 2020-12-18 17:45 UTC

**Comment by Danekjovax** [comment] 2020-12-18 17:51
I'll check Corail and see if there's something there that can help resolve this.  Thanks.

**Comment by Beserkerlel** [comment] 2020-12-18 17:59
@Danekjovax From what I can gather, tombstone-common config has the max time set to 1440 minutes or 24 hours max duration. The effects appear infinite (and practically are for game playing use if you're regularly killing apotheosis mobs) because minecraft itself displays anything longer than 27 minutes as "* *:* *" for a hard limit on the display, but is indeed counting down the 24 hours I'd guess. I would change their config to something more reasonable (and viewable) like 10-20 minutes max duration from the enchant. Hope that helps

**Comment by Danekjovax** [comment] 2020-12-19 12:14
@Beserkerlel Thanks for the help!  OK, I found the option here:

tombstone-common.toml, line159:
max_duration_magic_siphon = 1440

I am changing it to something more realistic, like 60.  Would be nice to scale it depending on the Siphon level, but this should make things a little more reasonable.
