### ISSUE TITLE
weird particle bug

### ISSUE THREAD

**Issue by tunaeskanaytac** [Shadows-of-Fire/Apotheosis#383] opened 2021-05-18 18:16 UTC
when I updated the mod these particles show up under my character's feet 
![2021-05-18_20 55 59](https://user-images.githubusercontent.com/13142062/118700805-b5e14800-b81b-11eb-8722-9e5c352ddc47.png)
![2021-05-18_20 56 11](https://user-images.githubusercontent.com/13142062/118700809-b7127500-b81b-11eb-8401-3a18b79e9ee3.png)

**Comment by Shadows-of-Fire** [comment] 2021-05-18 18:31
duplicate of #382
Just some weird leftover code that shouldn't have gone live

**Closed as completed by Shadows-of-Fire** 2021-05-18 18:31 UTC
