### ISSUE TITLE
Crash when rendering enchantment text

### ISSUE THREAD

**Issue by loving2** [Shadows-of-Fire/Apotheosis#1199] opened 2024-03-14 13:12 UTC
**Describe the bug**
Evilcraft's Blood Chest will repair an item with durability but has a chance of adding a negative enchantment. Apotheosis adds text to enchantments to describe them. When an Occultism Master Miner Marid has one of Evilcraft's enchantments on it, it appears to crash the client when trying to render the text from hovering the mouse over the item.

**To Reproduce**
1. Use an Occultism Master Miner Marid in a Dimensional Mineshaft to cause durability damage
2. Repair it in an Evilcraft Blood Chest until it has negative enchantments (not sure which enchantment causes the issue)
3. Mouse over the Occultism Master Miner Marid
4. Crash

**Expected behavior**
The client renders the text and doesn't crash.

**System (please complete the following information):**
- Apotheosis Version: 7.3.0
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: [ATM9 v0.2.51](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5125809)

**Additional context**
I uploaded the crash report along with it, not sure if this issue belongs elsewhere, but if this is the wrong spot let me know and I can make an issue elsewhere! I did post it on Occultism's github in [this issue](https://github.com/klikli-dev/occultism/issues/1078). I'm not sure if this requires an Occultism Master Miner Marid or would happen to anything with durability.
[crash-2024-03-12_17.00.58-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14602581/crash-2024-03-12_17.00.58-client.txt)

**Comment by Shadows-of-Fire** [comment] 2024-03-17 01:33
Duplicate of #1165

**Closed as completed by Shadows-of-Fire** 2024-03-17 01:33 UTC
