### ISSUE TITLE
Apotheosis fletching table not a villager job site

### ISSUE THREAD

**Issue by Syndaryl** [Shadows-of-Fire/Apotheosis#302] opened 2021-01-21 13:58 UTC
I am unable to create fletcher villagers using the Apotheosis fletching table. Check out Immersive Engineering and Buzzier Bees, they've created new villager workstations and might be able to show how to hook fletchers back up again?

**Comment by Syndaryl** [comment] 2021-01-21 13:58
This is version 1.16.3-4.4.1

**Comment by rexlManu** [comment] 2021-01-25 07:32
The mod author already fixed the bug but didnt updated the mod yet on curseforge, so the workaround is, to compile the mod self and update placebo.

**Comment by Syndaryl** [comment] 2021-01-25 13:09
Aha, perfect! Thanks a bunch!

**Comment by Shadows-of-Fire** [comment] 2021-01-25 15:36
duplicate of #285

**Closed as completed by Shadows-of-Fire** 2021-01-25 15:36 UTC
