### ISSUE TITLE
Crash on server start, usually for world creation 1.16.4

### ISSUE THREAD

**Issue by Letoric** [Shadows-of-Fire/Apotheosis#290] opened 2021-01-04 22:36 UTC
Crash log
https://pastebin.com/sua4phMC

This happens around 60-80% of the time for me, other people see it at varying levels. There is also a very similar, if not the same crash that happens on an existing world, with much lower consistency.

**Comment by Shadows-of-Fire** [comment] 2021-01-04 22:38
This is cauaed by psi, no amount of exceptions handling can block it from my end.  Supposibly it was fixed on psi's end, so try updating

**Closed as completed by Shadows-of-Fire** 2021-01-04 22:38 UTC

**Comment by Gbergz** [comment] 2021-01-06 14:14
Yeah this crash happens sometimes when server is starting, like 50% chance.
And yeah it seems like its caused by PSI. I'll see if I can report it there.
https://hatebin.com/arygcnnoph
