### ISSUE TITLE
[1.16.5] Client Crash when using Fletching Table

### ISSUE THREAD

**Issue by kalinzange** [Shadows-of-Fire/Apotheosis#450] opened 2021-09-03 14:02 UTC
Title Says All - If you place a Fletching Table and right-click on it, your client will crash but not a MP Server.

Minecraft Version: 1.16.5
Apotheosis Version: 4.7.1

[crash-2021-09-03_14.58.31-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7106396/crash-2021-09-03_14.58.31-client.txt)

**Comment by Shadows-of-Fire** [comment] 2021-09-04 16:49
duplicate of #441

**Closed as completed by Shadows-of-Fire** 2021-09-04 16:49 UTC

**Comment by kalinzange** [comment] 2021-09-04 19:58
Apologies, I saw the Issue was Closed and I though wasn't being traced
