### ISSUE TITLE
Potion Charm with Night Vision temporarily stops working for a few seconds occasionally 

### ISSUE THREAD

**Issue by x13x54** [Shadows-of-Fire/Apotheosis#392] opened 2021-05-26 21:49 UTC
We're using Apotheosis 4.4,1 as part of AllTheMods6-1.5.8b on a 8GB ram linux server. Due to performance reasons the tps can be a bit low.
The issue we're getting is that when we put an "Indestructible" enchantment (forbidden&arcanus) on the (night vision) potion charm it will leave you without night vision for a few seconds up to half a minute before it reapplies itself. This can be really annoying in caves with mobs, etc.
The cause of the issue is likely that the mod checks if i do not have the effect anymore, and with lower tps that can cause a gap in effect.
A way to fix this would be to reapply the effect shortly before it expires, for example. Sadly i found no way to change this in the mod that is currently running on our server.

**Comment by Shadows-of-Fire** [comment] 2021-06-01 06:05
A) the charm is non-enchantable, any method of throwing an enchantment on there is immediately unsupported behavior
B) The night vision charm already applies a longer-than-usual duration to avoid the flickering time.  You are encountering issues caused by TPS lag, that can only be fixed by increasing your TPS back to standard.

**Closed as completed by Shadows-of-Fire** 2021-06-01 06:05 UTC
