### ISSUE TITLE
Crash upon server launch

### ISSUE THREAD

**Issue by MichaelS608** [Shadows-of-Fire/Apotheosis#1079] opened 2023-11-17 09:08 UTC
[servercrashreportApotheosis.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13389732/servercrashreportApotheosis.txt)

I see a listener triggered, but unsure of what the index 3 is identifying:

```
[01:02:52] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: dev/shadowsoffire/placebo/reload/TypeKeyed
        Index: 3
        Listeners:
                0: NORMAL
                1: ASM: dev.shadowsoffire.apotheosis.Apotheosis$ModularDeferredHelper@40ea0ad5 register(Lnet/minecraftforge/registries/RegisterEvent;)V
                2: ASM: dev.shadowsoffire.apotheosis.ench.EnchModule@3488f950 miscRegistration(Lnet/minecraftforge/registries/RegisterEvent;)V
                3: ASM: dev.shadowsoffire.apotheosis.Apotheosis$ModularDeferredHelper@aaa6391 register(Lnet/minecraftforge/registries/RegisterEvent;)V
                4: ASM: dev.shadowsoffire.apotheosis.adventure.AdventureModule@12b171d0 miscRegistration(Lnet/minecraftforge/registries/RegisterEvent;)V
```

**Comment by MichaelS608** [comment] 2023-11-17 09:10
Should mention this is a server running 1.20.1 with most recent 1.20.1 versions for Apotheosis, ApothicAttributes, Patchouli, and Placebo

**Comment by Shadows-of-Fire** [comment] 2023-11-17 09:11
duplicate of #1077

**Closed as not planned by Shadows-of-Fire** 2023-11-17 09:11 UTC
