### ISSUE TITLE
Client crash (1.12.2)

### ISSUE THREAD

**Issue by mattlcoud** [Shadows-of-Fire/Apotheosis#1363] opened 2024-10-04 01:42 UTC
My game crashed after updating some mods. I'm not sure what produced it but my client says that the main potential cause is due to apotheosis

The mods I recently updated are:
_Legendary tooltips
Mahou Tsukai
Fermium Booter
Xaero's World Map
Rouglike Dungeons -- Fnar's Edition
Trinkets and Baubles
Lycanites Mobs
Future MC
RLCombat
Xaero's Minimap
Forgelin-Continuous_

Before updating these, everything was fine.

**Here is the crashlog:**
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-10-03 21:29:07 GMT-04:00
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/enchantment/EnchantmentHelper
    at shadows.ench.objects.ItemHellBookshelf.getSubItems(ItemHellBookshelf.java:46)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:587)
    at net.minecraft.client.Minecraft.init(Minecraft.java:529)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.enchantment.EnchantmentHelper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:406)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208)
    at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:71)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 13 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.bettercombatmod.json:EnchantmentHelperMixin from mod unknown-owner] from phase [INIT] in config [mixins.bettercombatmod.json] FAILED during APPLY
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:667)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:617)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:393)
    ... 18 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/enchantment/EnchantmentHelper::rlcombat_vanillaEnchantmentHelper_applyThornEnchantments with priority 1000 cannot inject into net/minecraft/enchantment/EnchantmentHelper::func_151384_a(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/entity/Entity;)V merged by org.dimdev.vanillafix.bugs.mixins.MixinEnchantmentHelper with priority 1000 [PREINJECT Applicator Phase -> mixins.bettercombatmod.json:EnchantmentHelperMixin from mod unknown-owner -> Prepare Injections ->  -> redirect$zzc000$rlcombat_vanillaEnchantmentHelper_applyThornEnchantments(Lnet/minecraft/entity/EntityLivingBase;)Lnet/minecraft/item/ItemStack; -> Prepare]
    at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
    at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377)
    ... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1179604968 bytes (1124 MB) / 5631901696 bytes (5371 MB) up to 11125391360 bytes (10610 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx11936m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 100 mods loaded, 100 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                    | Version              | Source                                          | Signature                                |
       |:----- |:--------------------- |:-------------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft             | 1.12.2               | minecraft.jar                                   | None                                     |
       | LCH   | mcp                   | 9.42                 | minecraft.jar                                   | None                                     |
       | LCH   | FML                   | 8.0.99.99            | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                 | 14.23.5.2859         | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | xaerominimap_core     | 1.12.2-1.0           | minecraft.jar                                   | None                                     |
       | LCH   | xaeroworldmap_core    | 1.12.2-1.0           | minecraft.jar                                   | None                                     |
       | LCH   | mixinbooter           | 9.1                  | minecraft.jar                                   | None                                     |
       | LCH   | fermiumbooter         | 1.1.1                | `FermiumBooter-1.1.1.jar                        | None                                     |
       | LCH   | aether_legacy         | 1.5.3.2              | aether-1.12.2-v1.5.4.0.jar                      | None                                     |
       | LCH   | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCH   | aether_baubles        | 1.0                  | aether_baubles-1.2.jar                          | None                                     |
       | LCH   | aiimprovements        | 0.0.1.3              | AIImprovements-1.12-0.0.1b3.jar                 | None                                     |
       | LCH   | aireducer             | 0.3.0                | AIReducer-1.12.2-0.3.0.jar                      | None                                     |
       | LCH   | placebo               | 1.6.0                | Placebo-1.12.2-1.6.1.jar                        | None                                     |
       | LCH   | apotheosis            | 1.12.4               | Apotheosis-1.12.2-1.12.5.jar                    | None                                     |
       | LCH   | jei                   | 4.16.1.1012          | jei_1.12.2-4.16.1.1012.jar                      | None                                     |
       | LCH   | appleskin             | 1.0.14               | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
       | LCH   | astralsorcery         | 1.10.27              | astralsorcery-1.12.2-1.10.27.jar                | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | quark                 | r1.6-179             | Quark-r1.6-179.jar                              | None                                     |
       | LCH   | autoreglib            | 1.3-32               | AutoRegLib-1.3-32.jar                           | None                                     |
       | LCH   | battletowers          | 1.6.5                | BattleTowers-Mod-1.12.2.jar                     | None                                     |
       | LCH   | bettercaves           | 1.12.2               | bettercaves-1.12.2-2.0.4.jar                    | None                                     |
       | LCH   | better_diving         | 1.5.8                | BetterDiving-1.12.2-1.5.8.jar                   | None                                     |
       | LCH   | bettermineshafts      | 1.12.2-2.2.1         | BetterMineshaftsForge-1.12.2-2.2.1.jar          | None                                     |
       | LCH   | betterplacement       | 1.0.0-1              | BetterPlacement-1.0.0-1.jar                     | None                                     |
       | LCH   | biomesoplenty         | 7.0.1.2445           | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar   | None                                     |
       | LCH   | birdsfoods            | 3.1 - [1.12]         | birdsfoods-1.12 - 3.1.jar                       | None                                     |
       | LCH   | callablehorses        | 1.1.1                | callablehorses-1.12.2-1.1.1.jar                 | None                                     |
       | LCH   | carryon               | 1.12.3               | carryon-1.12.2-1.12.7.23.jar                    | None                                     |
       | LCH   | ctm                   | MC1.12.2-1.0.2.31    | CTM-MC1.12.2-1.0.2.31.jar                       | None                                     |
       | LCH   | chisel                | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                    | None                                     |
       | LCH   | clumps                | 3.1.2                | Clumps-3.1.2.jar                                | None                                     |
       | LCH   | codechickenlib        | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux          | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
       | LCH   | cofhcore              | 4.6.6                | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
       | LCH   | cofhworld             | 1.4.0                | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
       | LCH   | comforts              | 1.4.1.3              | comforts-1.12.2-1.4.1.3.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | controlling           | 3.0.10               | Controlling-3.0.12.4.jar                        | None                                     |
       | LCH   | cookingforblockheads  | 6.5.0                | CookingForBlockheads_1.12.2-6.5.0.jar           | None                                     |
       | LCH   | thebetweenlands       | 3.9.6                | TheBetweenlands-3.9.6-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCH   | corpsecomplex         | 1.0.12.0             | corpsecomplex-1.12.2-1.0.12.0.jar               | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LCH   | ebwizardry            | 4.3.14               | ElectroblobsWizardry-4.3.14.jar                 | None                                     |
       | LCH   | elenaidodge           | 2.1                  | ElenaiDodge-1.12.2-2.1.jar                      | None                                     |
       | LCH   | enchdesc              | 1.1.20               | EnchantmentDescriptions-1.12.2-1.1.20.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | entityculling         | @VER@                | entityculling-1.12.2-1.6.3.jar                  | None                                     |
       | LCH   | extra_spells          | 1.2.0                | ExtraSpells-1.12.2-1.2.0.jar                    | None                                     |
       | LCH   | falling_tree          | 2.4.0                | FallingTree-1.12.2-2.4.0.jar                    | None                                     |
       | LCH   | forgelin_continuous   | 2.0.20.0             | Forgelin-Continuous-2.0.20.0.jar                | None                                     |
       | LCH   | forgelin              | 1.8.4                | Forgelin-Continuous-2.0.20.0.jar                | None                                     |
       | LCH   | futuremc              | 0.2.6                | Future-MC-0.2.20.jar                            | None                                     |
       | LCH   | grapplemod            | 1.12.2-v13           | grappling_hook_mod-1.12.2-v13.jar               | None                                     |
       | LCH   | highlighter           | 1.1.7                | Highlighter-1.12.2-forge-1.1.7.jar              | None                                     |
       | LCH   | waila                 | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
       | LCH   | llibrary              | 1.7.20               | llibrary-1.7.20-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire            | 1.9.1                | iceandfire-1.9.1-1.12.2.jar                     | None                                     |
       | LCH   | ironchest             | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                 | None                                     |
       | LCH   | legendarytooltips     | 1.1.9                | LegendaryTooltips-1.12.2-1.1.11.jar             | None                                     |
       | LCH   | letmedespawn          | 1.0                  | letmedespawn-1.12.2-forge-1.0.2.jar             | None                                     |
       | LCH   | lycanitesmobs         | 2.0.8.10 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.8.10.jar               | None                                     |
       | LCH   | mahoutsukai           | 1.12.2-v1.19.55      | mahoutsukai-1.12.2-v1.19.56.jar                 | None                                     |
       | LCH   | mantle                | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCH   | mcwbridges            | 1.0.6                | mcw-bridges-1.0.6b-mc1.12.2.jar                 | None                                     |
       | LCH   | millenaireextended    | 1.3.3                | Millenaire Extended-1.12.2-1.3.3.jar            | None                                     |
       | LCH   | millenaire            | Millénaire 8.1.2     | millenaire-8.1.2.jar                            | None                                     |
       | LCH   | mobends               | 1.2.1                | MoBends_1.12.2-1.2.1-19.12.21.jar               | None                                     |
       | LCH   | mousetweaks           | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                   | None                                     |
       | LCH   | naturescompass        | 1.8.5                | NaturesCompass-1.12.2-1.8.5-forge.jar           | None                                     |
       | LCH   | particleculling       | v1.4.3               | particleculling-1.12.2-v1.4.3.jar               | None                                     |
       | LCH   | pgwbandedtorches      | 0.9.20200801         | pgwbandedtorches-1.12.2-0.9.20200801.jar        | None                                     |
       | LCH   | prefab                | 1.3.1.7              | prefab-1.3.1.7.jar                              | None                                     |
       | LCH   | reachfix              | 1.0.10               | ReachFix-1.12.2-1.0.10.jar                      | None                                     |
       | LCH   | rfp2                  | 1.12.2-1.3.2         | RealFirstPerson2-1.12.2-1.3.2.jar               | None                                     |
       | LCH   | reevess_furniture_mod | 3.1.1                | Reeves'sFurnitureMod-3.1.1-1.12.2.jar           | None                                     |
       | LCH   | additionalstructures  | 2.5.0                | Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar  | None                                     |
       | LCH   | artifacts             | 1.1.2                | RLArtifacts-1.1.2.jar                           | None                                     |
       | LCH   | bettercombatmod       | 2.2.1                | RLCombat-1.12.2-2.2.1.jar                       | None                                     |
       | LCH   | roguelike             | 2.4.6                | RoguelikeDungeonsFnarEdition-1.12.2-2.4.6.jar   | None                                     |
       | LCH   | ruins                 | 17.2                 | Ruins-1.12.2.jar                                | None                                     |
       | LCH   | shouldersurfing       | 2.9.6                | ShoulderSurfing-1.12.2-2.9.6.jar                | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCH   | sit                   | v1.3                 | sit-1.12.2-v1.3.jar                             | None                                     |
       | LCH   | spartanshields        | 1.5.5                | SpartanShields-1.12.2-1.5.5.jar                 | None                                     |
       | LCH   | xat                   | 0.32.5               | Trinkets and Baubles-0.32.5.jar                 | None                                     |
       | LCH   | spartanweaponry       | 1.6.0                | SpartanWeaponry-1.12.2-1.6.0.jar                | None                                     |
       | LCH   | surge                 | 2.0.77               | Surge-1.12.2-2.0.77.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | texfix                | 4.0                  | TexFix V-1.12-4.0.jar                           | None                                     |
       | LCH   | thermalfoundation     | 2.6.7                | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
       | LCH   | thermalexpansion      | 5.5.7                | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
       | LCH   | thermalcultivation    | 0.3.6                | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
       | LCH   | thermaldynamics       | 2.5.6                | ThermalDynamics-1.12.2-2.5.6.1-universal.jar    | None                                     |
       | LCH   | travelersbackpack     | 1.0.35               | TravelersBackpack-1.12.2-1.0.35.jar             | None                                     |
       | LCH   | vanillafix            | 1.0.3                | VanillaIcecreamFix-1.0.3.jar                    | None                                     |
       | LCH   | walljump              | 1.3.2                | walljump-1.12.2-1.3.2.jar                       | None                                     |
       | LCH   | waystones             | 4.1.0                | Waystones_1.12.2-4.1.0.jar                      | None                                     |
       | LCH   | wrd                   | 0.8.0                | Wesley's Roguelike Dungeons V0.8.1.jar          | None                                     |
       | LCH   | xaerominimap          | 24.4.1               | Xaeros_Minimap_24.4.1_Forge_1.12.jar            | None                                     |
       | LCH   | xaeroworldmap         | 1.39.0               | XaerosWorldMap_1.39.0_Forge_1.12.jar            | None                                     |
       | LCH   | yungslaw              | 1.12.2               | YungsLaw-1.12.2-1.0.4.jar                       | None                                     |
       | LCH   | jade                  | 0.1.0                | Jade-0.1.0.jar                                  | None                                     |
       | LCH   | wizardryutils         | 1.12.2-1.2.3         | WizardryUtils-1.12.2-1.2.3.jar                  | None                                     |
       | LCH   | spellbundle           | 1.12.2-1.7.0         | SpellBundle-1.12.2-1.7.0.jar                    | None                                     |
  Loaded coremods (and transformers): FutureMC (Future-MC-0.2.20.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      Born in a Barn (Born In A Barn 1.8-1.12-1.2.jar)
                                        com.chocohead.biab.BornInABarn
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.6-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      FermiumBooter (`FermiumBooter-1.1.1.jar)
                                        
                                      ReachFixPlugin (ReachFix-1.12.2-1.0.10.jar)
                                        meldexun.reachfix.asm.ReachFixClassTransformer
                                      SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.6.0.jar)
                                        
                                      Forgelin-Continuous (Forgelin-Continuous-2.0.20.0.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_24.4.1_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.39.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      BetterCombat (RLCombat-1.12.2-2.2.1.jar)
                                        
                                      ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
                                        shadows.ApotheosisTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MixinBooter (!mixinbooter-9.1.jar)
                                        
                                      EntityCullingEarlyLoader (entityculling-1.12.2-1.6.3.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      AstralCore (astralsorcery-1.12.2-1.10.27.jar)
                                        
                                      MixinLoader (Highlighter-1.12.2-forge-1.1.7.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.4.3.jar)
                                        
                                      Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      ShoulderPlugin (ShoulderSurfing-1.12.2-2.9.6.jar)
                                        com.teamderpy.shouldersurfing.asm.ShoulderTransformer
                                      VanillaFixLoadingPlugin (VanillaIcecreamFix-1.0.3.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 560.70' Renderer: 'NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2'
  Suspected Mods: Apotheosis (apotheosis)
  Launched Version: forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 560.70, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: EclecticTrove-1.12.2-1.0.1.zip, Aether b1.7.3 Textures, Faithful 32x - 1.12.2.zip, Faithless1.12.zip, Emis_Rlcraft.zip, cassette music discs 1.11 - 1.12.2 v1.2.zip, 1.6.0v_VisualEnchantments(1.12).zip, Boss Bars+ 1.12.zip, RL SRP Better Visuals V0.1.zip, RL Better Shields V0.1.zip, Itsme64's smaller shield and totem1.12.2.zip, Refreshed Aether.zip, AnimEmis_InF_SW_Blue.zip, Lycanites Redux - v8.0.0.zip (incompatible), LycanitesMobs32X.zip, TZP 1.12.2_2.6.zip, RLTooltips.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

```

**Comment by Shadows-of-Fire** [comment] 2024-10-04 01:48
MC 1.12 is not supported.  Your crash here doesn't look related to Apoth anyway, you have a mixin conflict between Better Combat and Vanilla Fix.
`Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/enchantment/EnchantmentHelper::rlcombat_vanillaEnchantmentHelper_applyThornEnchantments with priority 1000 cannot inject into net/minecraft/enchantment/EnchantmentHelper::func_151384_a(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/entity/Entity;)V merged by org.dimdev.vanillafix.bugs.mixins.MixinEnchantmentHelper with priority 1000 [PREINJECT Applicator Phase -> mixins.bettercombatmod.json:EnchantmentHelperMixin from mod unknown-owner -> Prepare Injections ->  -> redirect$zzc000$rlcombat_vanillaEnchantmentHelper_applyThornEnchantments(Lnet/minecraft/entity/EntityLivingBase;)Lnet/minecraft/item/ItemStack; -> Prepare]
`

**Closed as completed by Shadows-of-Fire** 2024-10-04 01:48 UTC
