### ISSUE TITLE
[1.15.2] Apotheosis failed to load correctly

### ISSUE THREAD

**Issue by xor420** [Shadows-of-Fire/Apotheosis#220] opened 2020-09-12 16:39 UTC
Apotheosis failed to load correctly is what it says on game startup. I have the lib for it (Placebo) installed btw. Please help! You probably need more info than what i have provided here (aka. nothing) to resolve my problem so just ask for what you need and i will provide!

**Comment by xor420** [comment] 2020-09-12 16:42
I should also add that i currently don't have any other mods accept for this, placebo and WS tweaks so i don't think it can be a compatibility issue

**Comment by Shadows-of-Fire** [comment] 2020-09-12 17:03
Likely a duplicate of #219
Provide a log file and I'll check, but since that one is closed I'm going to close this as well until further information is provided.

**Closed as completed by Shadows-of-Fire** 2020-09-12 17:03 UTC

**Comment by xor420** [comment] 2020-09-12 17:08
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5213016/latest.log)
hope this helps

**Comment by Shadows-of-Fire** [comment] 2020-09-12 17:15
Oh, you just need to update forge.

**Comment by xor420** [comment] 2020-09-12 17:16
oh ok then, thank you for helping!

**Comment by xor420** [comment] 2020-09-12 17:24
it fixed a problem that i had with placebo too lol
