### ISSUE TITLE
Client crash in 6.1.2

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Apotheosis#817] opened 2023-03-20 15:39 UTC
mc 1.19.2
apoth 6.1.2

Occurs when attempting to use a vial of searing expulsion to remove a gem from a piece of armor the client crashes when mousing over the output slot/item when trying to pull it out of the smithing table.

crash log: https://gist.github.com/Saereth/b6038c6e4b9f1c831871609b846eb835

**Comment by mikaba-eu** [comment] 2023-03-20 18:19
MC: 1.19.2
Forge: 43.2.7
Apotheosis: 6.1.2

got exact the same error.
I tried to repair / combine a bow with a another on the smithingtable. As soon as I hover over the output, the game crashes.

[crash-2023-03-20_19.15.15-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11021654/crash-2023-03-20_19.15.15-client.txt)

**Comment by phorced** [comment] 2023-03-20 20:50
MC: 1.19.2
Forge: 43.2.6
Apotheosis: 6.1.2

similar but not the same reason 
used mekanism so may want to add that to the testing environment to find this one

command to past in minecraft for items (using a mekanism mekasuit armor piece):
'''
/setblock ~ ~ ~ minecraft:chest[facing=east,type=single,waterlogged=false]{Items:[{Count:1b,Slot:0b,id:"mekanism:mekasuit_pants",tag:{affix_data:{affixes:{"apotheosis:armor/attribute/fortunate":0.98161685f,"apotheosis:armor/attribute/ironforged":0.13730067f,"apotheosis:armor/attribute/stalwart":0.30357897f,"apotheosis:armor/attribute/steel_touched":0.7700275f,"apotheosis:armor/dmg_reduction/blockading":0.49786127f,"apotheosis:armor/dmg_reduction/runed":0.16563702f,"apotheosis:durable":0.47f,"apotheosis:socket":2.0f},name:'{"color":"#ED7014","translate":"%s %s %s","with":[{"translate":"affix.apotheosis:armor/attribute/steel_touched"},"",{"translate":"affix.apotheosis:armor/attribute/ironforged.suffix"}]}',rarity:"mythic"},mekData:{EnergyContainers:[{Container:0b,stored:"16000000"}]}}},{Count:1b,Slot:1b,id:"apotheosis:superior_sigil_of_socketing",tag:{}}]}
'''

And Log with crash report

[2023-03-20-2.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11022964/2023-03-20-2.log)

[crash-2023-03-20_22.33.33-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11022961/crash-2023-03-20_22.33.33-client.txt)

**Comment by rtxyd** [comment] 2023-03-21 03:07
I encounter the same issue and has post this, see #813 and change log, this will be fixed in 6.1.3.

**Comment by Shadows-of-Fire** [comment] 2023-03-22 02:10
duplicate of #813

**Closed as completed by Shadows-of-Fire** 2023-03-22 02:10 UTC
