### ISSUE TITLE
Apotheosis crashed at launch

### ISSUE THREAD

**Issue by Klouver-github** [Shadows-of-Fire/Apotheosis#515] opened 2022-01-24 00:01 UTC
I tried launching but then crashed when launching, I dont have any incompatible mods installed https://paste.gg/p/anonymous/21294c659bda42919b826b7521f45a59

**Comment by Shadows-of-Fire** [comment] 2022-01-24 00:04
That log appears to be truncated, you'll need to provide the full log for assistance.

**Comment by Klouver-github** [comment] 2022-01-24 00:45
here is the full debug log https://paste.gg/p/anonymous/967bd56c529142e7a050e84d3729692d

**Comment by Shadows-of-Fire** [comment] 2022-01-24 00:48
Hm, there's still not an error in that whole log, so I'm not sure what's going on.
Technically speaking there are more incompatible mods than the ones that I know of.
You may want to see if the issue is fixed with 5.1.1, you might be having the same problem as #514

**Comment by Klouver-github** [comment] 2022-01-24 01:03
crashed at launch again, sent me back to launch tab https://paste.gg/p/anonymous/8f52b81ae8de4a8088c4ad0f9b060690

**Comment by Shadows-of-Fire** [comment] 2022-01-24 01:24
Yeah there's still not a crash in that report; you probably have a mod conflict that is arising from some sort of ASM/Mixin level issue.  The only way to track that down is to remove mods until it stops, and then source the conflicting mod.

**Comment by Klouver-github** [comment] 2022-01-24 01:26
could it be some enchantment conflicts or anvil conflicting or certain category

**Comment by Klouver-github** [comment] 2022-01-24 01:29
i do also have some mods that changes mob spawners, but i have no enhanced spawner

**Comment by Shadows-of-Fire** [comment] 2022-01-24 01:57
Identified to be an incompatibility with https://www.curseforge.com/minecraft/mc-mods/xpisnoobject

**Closed as completed by Shadows-of-Fire** 2022-01-24 01:57 UTC
