### ISSUE TITLE
Apotheosis 1.19.2 Not functioning 

### ISSUE THREAD

**Issue by Zelioth** [Shadows-of-Fire/Apotheosis#683] opened 2022-10-22 04:20 UTC
Minecraft 1.19.2
Forge 43.1.47
Mod Pack : Friends United. 

Tried testing the new update for 1.19.2 but it's just broke 

[21.10 23:13:20] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_boots/rare/EFFECT/0.33!
[21.10 23:13:20] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_chestplate/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_chestplate/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_boots/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:21] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:22] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:22] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:22] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:24] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_chestplate/rare/EFFECT/0.33!
[21.10 23:13:24] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_leggings/rare/EFFECT/0.33!
[21.10 23:13:24] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_chestplate/rare/EFFECT/0.33!
[21.10 23:13:24] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_chestplate/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_helmet/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_chestplate/rare/EFFECT/0.33!
[21.10 23:13:25] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_boots/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_helmet/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_chestplate/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_boots/rare/EFFECT/0.33!
[21.10 23:13:26] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:27] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_chestplate/rare/EFFECT/0.33!
[21.10 23:13:27] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:27] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:27] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_chestplate/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_chestplate/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_leggings/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_helmet/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_leggings/rare/EFFECT/0.33!
[21.10 23:13:28] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_chestplate/rare/EFFECT/0.33!
[21.10 23:13:29] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_chestplate/rare/EFFECT/0.33!
[21.10 23:13:29] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:29] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:30] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:30] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_chestplate/rare/EFFECT/0.33!
[21.10 23:13:30] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:30] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:31] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:31] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_helmet/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_leggings/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:32] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:33] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/rare/EFFECT/0.33!
[21.10 23:13:33] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/rare/EFFECT/0.33!
[21.10 23:13:33] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:33] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/rare/EFFECT/0.33!
[21.10 23:13:33] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_leggings/rare/EFFECT/0.33!
[21.10 23:13:34] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:35] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:35] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_boots/rare/EFFECT/0.33!
[21.10 23:13:35] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:35] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_chestplate/rare/EFFECT/0.33!
[21.10 23:13:36] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_boots/rare/EFFECT/0.33!
[21.10 23:13:36] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:36] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_chestplate/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:netherite_boots/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_chestplate/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_helmet/rare/EFFECT/0.33!
[21.10 23:13:37] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_helmet/rare/EFFECT/0.33!
[21.10 23:13:38] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/rare/EFFECT/0.33!
[21.10 23:13:38] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:38] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/rare/EFFECT/0.33!
[21.10 23:13:38] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/rare/EFFECT/0.33!
[21.10 23:13:39] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/rare/EFFECT/0.33!
[21.10 23:13:39] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/rare/EFFECT/0.33!
[21.10 23:13:39] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_leggings/rare/EFFECT/0.33!
[21.10 23:13:39] [Server] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_leggings/rare/EFFECT/0.33!

**Comment by Shadows-of-Fire** [comment] 2022-10-22 07:53
duplicate of #682

**Closed as completed by Shadows-of-Fire** 2022-10-22 07:53 UTC
