### ISSUE TITLE
[Niche Bug] Incompat with AdventureZ

### ISSUE THREAD

**Issue by Idefkftt** [Shadows-of-Fire/Apotheosis#1194] opened 2024-03-13 03:57 UTC
As the title suggests I know this is incredibly niche and thus not really something to be too concerned about, but just for thorough documentation's sake, Apotheosis appears to be incompatible with AdventureZ when running it on a 1.20.1 Forge client through the Connector mod.  Both work fine independently, but together causes the game to crash out with a returned exit code 1.  Not sure if it's Apotheosis throwing a fit or AdventureZ, but I'll be posting this issue to both just in case.

**Comment by Shadows-of-Fire** [comment] 2024-03-13 03:58
duplicate of https://github.com/Shadows-of-Fire/Apotheosis/issues/1106

**Closed as completed by Shadows-of-Fire** 2024-03-13 03:58 UTC
