### ISSUE TITLE
Server and login spam noting recipes continually added/removed

### ISSUE THREAD

**Issue by Bidgam** [Shadows-of-Fire/Apotheosis#584] opened 2022-06-15 23:18 UTC
I'm not sure if this is Apotheosis or some other mod's fault, so apologies if this is incorrect.

In the server logs and also when a player logs in, you see a bunch of Apotheosis recipes being loaded (in-game) and then the server shows as unloaded "Tried to load unrecognized recipe: apotheosis: (recipe name here) removed now).

This happens every single time a player logs in:

[17:28:33] [Server thread/INFO] [ne.mi.co.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@228ce032
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:crystal_seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:boots_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:beeshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:helmet_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:library removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:glowing_hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:melonshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:pearl_endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:enchanted_golden_apple removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:other_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:scrap_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:bow_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:heart_seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:pickaxe_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:weapon_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:blazing_hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:fishing_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:draconic_endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:prismatic_web removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:chestplate_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:ender_lead removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:leggings_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:crystal_seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:boots_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:beeshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:helmet_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:library removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:glowing_hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:melonshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:pearl_endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:enchanted_golden_apple removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:other_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:scrap_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:bow_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:heart_seashelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:pickaxe_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:weapon_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:blazing_hellshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:fishing_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:draconic_endshelf removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:prismatic_web removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:chestplate_tome removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:ender_lead removed now.
[17:28:33] [Server thread/ERROR] [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: apotheosis:leggings_tome removed now.

**Comment by Shadows-of-Fire** [comment] 2022-06-24 03:32
Duplicate of #574

**Closed as completed by Shadows-of-Fire** 2022-06-24 03:32 UTC
