### ISSUE TITLE
[Bug] Disabling the Adventure Module causes NullPointerException

### ISSUE THREAD

**Issue by johnrrowe** [Shadows-of-Fire/Apotheosis#1323] opened 2024-08-17 02:45 UTC
I recently updated to 1.20.1-7.4.1, and the game crashes on startup with a null pointer exception. I was able to replicate on a new instance with the only config change being that the Adventure Module is disabled.

The important snippet seems to be:
```
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
    Suppressed: java.lang.NullPointerException: Registry Object not present: apotheosis:gem
		at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?] {}
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.20.1-47.3.0-universal.jar%23169!/:?] {re:mixin,re:classloading}
		at dev.shadowsoffire.apotheosis.adventure.client.AdventureModuleClient$ModBusSub.lambda$client$3(AdventureModuleClient.java:162) ~[Apotheosis-1.20.1-7.4.1.jar%23160!/:7.4.1] {re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
```

Forge Version: 47.3.0
Game Version: 1.20.1
Mod Version: 7.4.1

[crash-2024-08-16_22.36.01-client.txt](https://github.com/user-attachments/files/16643149/crash-2024-08-16_22.36.01-client.txt)

**Comment by Shadows-of-Fire** [comment] 2024-08-17 02:47
Duplicate of #1322

**Closed as completed by Shadows-of-Fire** 2024-08-17 02:47 UTC

**Comment by johnrrowe** [comment] 2024-08-17 02:51
My apologies
