### ISSUE TITLE
ReforgingTable only on Server wrong attributes on gear

### ISSUE THREAD

**Issue by Tigger1992** [Shadows-of-Fire/Apotheosis#1150] opened 2024-02-07 08:03 UTC
Hello, i am playing ATM9 and it uses Apotheosis version 7.2.2 and i noticed that when i reforge an item it ends up getting change to something different than what was displayed in the reforging table. i tested it on single player and there it was all fine and as its supposed to be.i hope that github is the correct way to inform about this bug and i hope the images help to show the issue(3pictures always belong toghether[before/changeInto/result]):
![1Before](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/97bed163-16f7-43e9-ace7-c28270033a2d)
![1changeinto](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/91a29425-f469-4866-9448-79c3337348ae)
![1result](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/6ff5eff9-d9b7-412c-8def-1dbdbcc58051)
![2before](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/65b6ed63-3e6f-4998-9ce5-d5ac324ad0f4)
![2changeinto](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/9e48b11d-1a77-450e-b74a-e11dc5e7f42b)
![2result](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/1bc617a8-8f15-42f9-acd6-7a9998ac9fa1)
![3before](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/d7a96f39-fb7e-41a4-8770-4898fd3eaf13)
![3changeinto](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/d8f22e32-3d3c-4c52-9213-e7a0c9773feb)
![3result](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/6044d5ea-7e5f-4550-a629-751a0eb21e79)
![4before](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/5dbf5bbc-18b6-4864-aa6b-b6f2c0571222)
![4changeinto](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/1b4b96b5-74fe-4c59-a79b-b8ca6cd1f7d4)
![4result](https://github.com/Shadows-of-Fire/Apotheosis/assets/159237424/99a165d8-509d-4532-814a-c6def4bd7c30)

**Comment by SiverDX** [comment] 2024-02-07 09:03
See https://github.com/Shadows-of-Fire/Apotheosis/issues/1145

**Comment by Shadows-of-Fire** [comment] 2024-02-08 22:12
Duplicate of #1145

**Closed as completed by Shadows-of-Fire** 2024-02-08 22:12 UTC
