### ISSUE TITLE
Fletching table is broken.

### ISSUE THREAD

**Issue by Ultimum-Aeternum** [Shadows-of-Fire/Apotheosis#308] opened 2021-01-28 19:08 UTC
Basically apothesis broke fletching table.
It has overwrote vanilla fletching table and now it does not work.
I mean it's pretty ironic that you can't have and trade with "Fletcher villager" because of "overwritten" fletching table that is in "Village Module".
Villager just refuses to recognize it's as workstation.
Please fix.
But i mean there is solution, but then wandering traders have no trades.

**Comment by Shadows-of-Fire** [comment] 2021-01-28 19:09
duplicate of #285

**Closed as completed by Shadows-of-Fire** 2021-01-28 19:09 UTC
