### ISSUE TITLE
[1.18.2] Crash with mobs form EvilCraft

### ISSUE THREAD

**Issue by danzio** [Shadows-of-Fire/Apotheosis#633] opened 2022-08-24 06:17 UTC
I got crash while encountering some mobs from EvilCraft (Netherfishes). Had Apotheosis armor and sword while encountering. Now when I try to run save I have this crash message in launcher:
```
The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Can't find attribute apotheosis:current_hp_damage
```
Detailed crash report is attached:
[crash-2022-08-24_08.51.22-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9413335/crash-2022-08-24_08.51.22-server.txt).
Apotheosis version 5.5.1, EvilCraft version 1.2.6.

**Comment by Shadows-of-Fire** [comment] 2022-08-24 06:23
Duplicate of #629 

(evilcraft bug)

**Closed as completed by Shadows-of-Fire** 2022-08-24 06:23 UTC
