### ISSUE TITLE
1.19.2 Apotheosis has failed to load correctly

### ISSUE THREAD

**Issue by Snow5Wolf** [Shadows-of-Fire/Apotheosis#981] opened 2023-08-14 14:06 UTC
My game failed to load when I updated Apotheosis to the latest version today.
This is the crash report
[crash-2023-08-14_20.55.00-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12335650/crash-2023-08-14_20.55.00-fml.txt)

**Comment by ModernGamingWorld** [comment] 2023-08-14 17:09
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/12337713/latest.log)
Heres the Latest log for this crash on 1.19.2, since I saw the Snow only provided the Crash Report

**Comment by P3rf3ctXZer0** [comment] 2023-08-14 17:45
https://gist.github.com/P3rf3ctXZer0/1ded78e25a4c925477a3b8ecff828fcf

[14Aug2023 12:07:47.979] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: apotheosis, class shadows.apotheosis.Apotheosis
java.lang.NoClassDefFoundError: dev/shadowsoffire/placebo/json/ItemAdapter
	at dev.shadowsoffire.apotheosis.village.wanderer.WandererReplacements.<clinit>(WandererReplacements.java:37) ~[Apotheosis-1.19.2-6.3.4.jar%23680!/:6.3.4]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.2.21.jar%231169!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.2.21.jar%231169!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.2.21.jar%231169!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.21.jar%231168!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.shadowsoffire.placebo.json.ItemAdapter
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 15 more

**Comment by Shadows-of-Fire** [comment] 2023-08-14 21:10
Yeah gradle decided it wanted to ship the 1.20 code in the 1.19 jar, resolved in 6.3.5

**Closed as completed by Shadows-of-Fire** 2023-08-14 21:10 UTC
