### ISSUE TITLE
[1.18.2 Bug] NBT Tags 

### ISSUE THREAD

**Issue by LunafeyLazuli** [Shadows-of-Fire/Apotheosis#744] opened 2022-12-12 14:46 UTC
For some reason, Apotheosis is trying to apply NBT tags to things that aren't weapons or armor, preventing things from stacking correctly. For example, if you attack a zombie with bread in your hand, the bread will now have <apoth.equipment: 1b> so it can't stack with normal bread that doesn't have that NBT tag. 
https://i.gyazo.com/1a0eae51c56b03d22978ff73be094403.png

Forge - 40.1.85
Apotheosis - 1.18.2-5.7.7.jar

**Comment by enimog** [comment] 2022-12-18 22:28
I have the same issue for 1.19.2

**Comment by rgmoon** [comment] 2022-12-21 05:25
Well same here, I thought it was big stack mod's problem, but seems like it's not
Edit:1.19.2 too

**Comment by Shadows-of-Fire** [comment] 2023-01-02 04:18
This was fixed in 5.7.6 for 1.18, but it has yet to be resolved in 1 19

**Comment by ViRb3** [comment] 2023-01-05 22:55
Manual workaround — put the affected items in a regular vanilla chest, stand on top of it, then run this command as OP:
```
/data remove block ~ ~ ~ Items[{}].tag."apoth.equipment"
```
Can also automate with command block and a button or repeater.

@Shadows-of-Fire Is the cause unknown for 1.19, or has the fix simply not been ported?

**Comment by HeavyDeception** [comment] 2023-01-22 06:40
Ok, this is happening still wanted to just update this.

https://puu.sh/Jxhm0/c33368450b.mp4

**Comment by Shadows-of-Fire** [comment] 2023-01-23 07:00
I'm honestly unsure if the fix for this was published in 6.0.3 - it will be published in 6.1.0, but 6.0.3 is sort of a phantom-build, so it may be in there.

**Comment by sreny1** [comment] 2023-02-11 07:11
so is this fix not comming to the 1.18.2 version? :(

**Comment by Shadows-of-Fire** [comment] 2023-02-11 07:12
> This was fixed in 5.7.6 for 1.18

**Comment by sreny1** [comment] 2023-02-11 07:28
i am playing all the mods gravitas right now, it has version 5.7.7 and i stil get this bug :(
i think it happens to items that i have in my offhand, not sure what exactly triggers it

**Comment by sreny1** [comment] 2023-02-11 20:12
![2023-02-11_21 11 22](https://user-images.githubusercontent.com/101481389/218279190-657f1ab9-a9d4-4dec-9cfe-02942cc6c2cd.png)

**Comment by Shadows-of-Fire** [comment] 2023-03-04 08:21
The fixed code is here and is published in the latest 1.18 release - https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/affix/effect/FestiveAffix.java#L91-L99
This removes that tag from all drops that go through the `LivingDropsEvent`, which should be all entity drops.  If a mod doesn't process drops through the event, they're violating the contract.

**Closed as completed** 2023-03-07 04:51 UTC
