### ISSUE TITLE
Server crash with player login

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Shadows-of-Fire/Apotheosis#175] opened 2020-05-17 21:48 UTC
Whenever one of our players logs onto our server it crashes. We ended up having to delete the region.

https://pastebin.com/qdfHP2jQ

**Comment by Shadows-of-Fire** [comment] 2020-05-18 02:10
duplicate of #168 (update the mod)

**Closed by Shadows-of-Fire** 2020-05-18 02:10 UTC
