### ISSUE TITLE
Nether Star modification not working

### ISSUE THREAD

**Issue by TheeMX** [Shadows-of-Fire/Apotheosis#186] opened 2020-07-01 21:48 UTC
I created a mob farm about 300 or so blocks away from my base, and threw a chunkloader down and used the Nether star modification on a cave spider spawner. The chunkloader is from the Persistant Bits mod. I definitely know the chunkloader works because I have a bonsai pot farm around 200 blocks away from my base and it continues to put items into my refined storage system, but the amount of string in my system is stationary when I'm at my base. Using the Valhelsia 2 mod pack if that helps

**Comment by Shadows-of-Fire** [comment] 2020-07-04 22:10
Cannot reproduce, although it may have been inadvertently fixed in the upcoming version (there's been a lot of changes since last release).

Please update this if it keeps happening after the next update drops.

**Closed as completed by Shadows-of-Fire** 2020-07-04 22:10 UTC

**Comment by wootaboot** [comment] 2020-07-26 00:56
I too am having this issue, im on 1.12 however. im using FTB utilities.
