### ISSUE TITLE
Cant Joint Server

### ISSUE THREAD

**Issue by Deathawaits4** [Shadows-of-Fire/Apotheosis#405] opened 2021-06-19 13:23 UTC
With this mod installed and the newest forge version i can not longer join the server. I keep getting the message: "Interal Exception: io.netty.handler.codec.DecoderException: Java.lang.IndexOutOfBoundsException: Index: 25, Size: 5

This is 100% only with this mod installed and no other. The server starts without issues and single player also works without issues. I also dont get any logs.

**Comment by Shadows-of-Fire** [comment] 2021-06-24 23:54
Provide debug logs from both client and server

**Comment by NoticeRL** [comment] 2021-07-01 15:23
I'm having the same issue, gives me hope that it can be solved though because I also have apotheosis in my modpack. 
Speculation from many things seems to point to that it COULD be a username length issue, but mine is already extremely short and I made it shorter and it didn't change anything. 

I don't know if I can get logs because as Deathawaits4 said, its not server side and I also don't get any logs. 

Would love to hear any ideas about this.

**Comment by InteJason** [comment] 2021-07-04 09:07
same, the client log here: https://paste.ee/p/zLrTy

**Comment by IchigoGames** [comment] 2021-07-05 22:03
Same issue i with my new pack but i have the same mod in another pack and no issue so im thinking its a mod compatibility issue
that or a issue with forge 36.1.32 1.16.5

**Comment by Shadows-of-Fire** [comment] 2021-07-10 01:52
Someone else reported a similar issue occuring when Scaling Health was installed

**Comment by InteJason** [comment] 2021-07-10 13:32
I don't have scaling health installed. But the issue still exists.

**Comment by Shadows-of-Fire** [comment] 2021-07-21 04:39
Apoth's development end has been updated to Forge 36.1.65.  I am able to connect to dedicated servers with Apoth, Placebo, JEI, and Jade installed with no issues.  Closing as non-reproducible.

**Closed as completed by Shadows-of-Fire** 2021-07-21 04:39 UTC
