### ISSUE TITLE
Villagers and fletching table

### ISSUE THREAD

**Issue by ItzEnderArkail** [Shadows-of-Fire/Apotheosis#336] opened 2021-03-13 05:42 UTC
i was playing a little bit and seems like villagers will not take the fletching table for the fletcher profession maybe because the mod modified the table and villagers don't detect the table as a workstation

**Comment by juanretamales** [comment] 2021-03-13 22:22
It is another mod that has the conflict, I have the same problem and I thought it was another mod (in my case easy villager) but I did an adventure with that mod and this one, and I managed to convert it, even though it does not always work outside the easy villager.
Either way, I'm trying to find the other mod that's causing the conflict. 
![2021-03-13_19 22 06](https://user-images.githubusercontent.com/8421263/111051396-73714880-8431-11eb-9b1e-2a70958e9642.png)

pd: according to my tests it is much more difficult to convert him to fletcher than to another profession 
pd2: in other thread, i read who is fix in dev version

**Comment by Shadows-of-Fire** [comment] 2021-03-16 19:57
duplicate of #285

**Closed as completed by Shadows-of-Fire** 2021-03-16 19:57 UTC
