### ISSUE TITLE
Issue with the icy thorns enchant

### ISSUE THREAD

**Issue by celittle3** [Shadows-of-Fire/Apotheosis#28] opened 2019-04-05 04:21 UTC
I was trying to update MobGrindingUtilities and got this.  His comments are below.  Thanks.

MC 1.12.2 Forge 2768 MobGrindingUtil 0.3.12. Crash on dedicated server. I did notice there is an update 0.3.13, will that have an effect on this issue?
Thanks for a great mod.

WARNING: coremods are present:
RandomPatches (randompatches-1.12.2-1.14.0.0.jar)
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
EnderCorePlugin (EnderCore-1.12.2-0.5.44.jar)
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
ForgelinPlugin (Forgelin-1.8.2.jar)
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
LoadingPlugin (RandomThings-MC1.12.2-4.2.6.jar)
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
LoadingPlugin (AdChimneys-1.12.2-3.3.18.0-build.0262.jar)
CorePlugin (ForgeEndertech-1.12.2-4.4.10.0-build.0264.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
ApotheosisCore (Apotheosis-1.12.2-1.6.3.jar)
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.3.jar)
LoadingPlugin (Quark-r1.5-144.jar)
llibrary (llibrary-core-1.0.8-1.12.2.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/7/19 1:09 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:1187)
at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:748)
at shadows.ench.enchantments.EnchantmentIcyThorns.func_151367_b(EnchantmentIcyThorns.java:48)
at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:465)
at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:608)
at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:168)
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1401)
at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425)
at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:99)
at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:63)
at net.minecraft.world.World.func_72939_s(World.java:1835)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.entity.player.EntityPlayerMP.func_70670_a(EntityPlayerMP.java:1187)
at net.minecraft.entity.EntityLivingBase.func_70690_d(EntityLivingBase.java:748)
at shadows.ench.enchantments.EnchantmentIcyThorns.func_151367_b(EnchantmentIcyThorns.java:48)
at net.minecraft.enchantment.EnchantmentHelper$HurtIterator.func_77493_a(EnchantmentHelper.java:465)
at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:608)
at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:134)
at net.minecraft.enchantment.EnchantmentHelper.func_151384_a(EnchantmentHelper.java:168)
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1401)
at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425)
at mob_grinding_utils.tile.TileEntitySaw.activateBlock(TileEntitySaw.java:99)
at mob_grinding_utils.tile.TileEntitySaw.func_73660_a(TileEntitySaw.java:63)

-- Block entity being ticked --
Details:
Name: minecraft:tile.mob_grinding_utils.saw // mob_grinding_utils.tile.TileEntitySaw
Block type: ID #3152 (tile.mob_grinding_utils.saw // mob_grinding_utils.blocks.BlockSaw // mob_grinding_utils:saw)
Block data value: 12 / 0xC / 0b1100
Block location: World: (-119,88,274), Chunk: (at 9,5,2 in -8,17; contains blocks -128,0,272 to -113,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Actual block type: ID #3152 (tile.mob_grinding_utils.saw // mob_grinding_utils.blocks.BlockSaw // mob_grinding_utils:saw)
Actual block data value: 12 / 0xC / 0b1100
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1835)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
Level name: Unexplored
All players: 1 total; [EntityPlayerMP['Wreckage'/757510, l='Unexplored', x=-120.04, y=85.00, z=269.38]]
Chunk stats: ServerChunkCache: 1530 Drop: 0
Level seed: 5496094115214410642
Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
Level generator options:
Level spawn location: World: (-9,68,250), Chunk: (at 7,4,10 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 99627990 game time, 100905756 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 12517 (now: true), thunder time: 7980 (now: true)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Linux (amd64) version 4.9.144-xxxx-std-ipv6-64
Java Version: 1.8.0_192, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 2455437040 bytes (2341 MB) / 5797052416 bytes (5528 MB) up to 7635730432 bytes (7282 MB)
JVM Flags: 2 total; -Xmx8192M -Xms512M
IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
FML: MCP 9.42 Powered by Forge 14.23.5.2768 202 mods loaded, 202 mods active
@vadis365
Owner
vadis365 commented 4 days ago

Hello,
This isn't an issue with MGU by the looks of things. One of the other mods you are using adds some sort of enchant to players which cannot be applied to fake players like the Mob Masher.

at shadows.ench.enchantments.EnchantmentIcyThorns.func_151367_b(EnchantmentIcyThorns.java:48)

Whatever mod adds 'Icy Thorns' Enchant is what is causing it. Please report it to the authour of that mod and ask if he could a a check for instances of fake players as it will cause issues in other mods too,
Cheers,
Me.

**Comment by vadis365** [comment] 2019-04-05 11:17
I think this issue has already been fixed in Apotheosis - Shadows can confirm. :)

**Comment by Shadows-of-Fire** [comment] 2019-04-06 06:47
Duplicate of #21 (has been fixed already)

**Closed by Shadows-of-Fire** 2019-04-06 06:47 UTC
