### ISSUE TITLE
Mod causing server to crash on boot

### ISSUE THREAD

**Issue by purestone9** [Shadows-of-Fire/Apotheosis#267] opened 2020-12-09 20:29 UTC
Im running an AllTheMods 6 Server and updated the Envirotech Mods and Valkarie Lib
After updating those mods Apothesis keeps causing the server to crash and run in a boot loop

Minecraft Version 1.16.4
Forge Version forge-1.16.4-35.1.4
Crash Log https://pastebin.com/yRtWurmj

**Comment by Shadows-of-Fire** [comment] 2020-12-09 20:32
Duplicate of #255 (caused by psi, should be fixed on their end already)

**Closed as completed by Shadows-of-Fire** 2020-12-09 20:32 UTC

**Comment by purestone9** [comment] 2020-12-09 20:53
How dose Psi have anything to do with this?
