### ISSUE TITLE
[BUG] (1.20) Vial of Arcane Extraction does not work on Smithing Table

### ISSUE THREAD

**Issue by Tazion03** [Shadows-of-Fire/Apotheosis#1016] opened 2023-09-11 20:21 UTC
When you place gemmed item, and vial in table nothing happens.
![Screenshot 2023-09-11 151104](https://github.com/Shadows-of-Fire/Apotheosis/assets/144735108/656cea74-9c94-4b28-993b-6c88534171f3)

**Comment by Tazion03** [comment] 2023-09-11 20:22
![Screenshot 2023-09-11 152233](https://github.com/Shadows-of-Fire/Apotheosis/assets/144735108/44923291-6c48-42d4-b0ae-170bf875c34a)

**Comment by TPNils** [comment] 2023-09-23 01:08
Also encountered this issue. Was curious of the wiki was not up to date and wanted to look at the recipe. I _think_ the issue is located here: https://github.com/Shadows-of-Fire/Apotheosis/blob/1176c37bc8cb98f395788a097427ba9164c31e85/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/socket/ExtractionRecipe.java#L34

I think that line should say `pInv.getItem(BASE)`, not `pInv.getItem(0)`

**Comment by rexzooly** [comment] 2023-09-26 15:11
I can also confirm this problem I am using 1.20.1 Apotheosis-1.20.1-7.0.5.jar making all these items useless and littering our server/world this doesn't work in the Smithing  table anymore

**Comment by Dimaqxt** [comment] 2023-11-05 20:08
> Also encountered this issue. Was curious of the wiki was not up to date and wanted to look at the recipe. I _think_ the issue is located here:
> 
> https://github.com/Shadows-of-Fire/Apotheosis/blob/1176c37bc8cb98f395788a097427ba9164c31e85/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/socket/ExtractionRecipe.java#L34
> 
> I think that line should say `pInv.getItem(BASE)`, not `pInv.getItem(0)`

Is there a way to fix this within the code by yourself? How do you access it?

**Comment by AuxAtlas** [comment] 2023-11-13 12:37
Submitted a pr [here](https://github.com/Shadows-of-Fire/Apotheosis/pull/1073) with a purposed fix to this issue.

For those wanting the standard Apotheosis version 7.0.5 with only this problem fixed on top of it, you may download a fixed version of 7.0.5 [here](https://github.com/VenomCodeDev/Apotheosis/releases/tag/7.0.5.1)

**Closed as completed** 2023-11-16 12:07 UTC
Labels: bug
