### ISSUE TITLE
Anvil's not splitting items.

### ISSUE THREAD

**Issue by Shatokan0** [Shadows-of-Fire/Apotheosis#751] opened 2022-12-26 12:46 UTC
In Direwolf20 1.19 v1.0.4, an anvil with splitting, and obliteration on it are not splitting enchanting books.

https://user-images.githubusercontent.com/45337359/209550566-56e2e639-7194-4c1a-bb5a-93a0d29f29f0.mp4

Tested using 2 different anvils, and 4 different books.

**Comment by Shadows-of-Fire** [comment] 2023-01-02 04:14
Duplicate of #736 

This was fixed by #727 but that fix has not yet been published.  It will arrive in 6.1.0.

Fortunately the library can achieve everything splitting and obliteration can

**Closed as completed by Shadows-of-Fire** 2023-01-02 04:14 UTC
