### ISSUE TITLE
Hello, I am your fan, I have a crash here, but I don't know why

### ISSUE THREAD

**Issue by mcmso** [Shadows-of-Fire/Apotheosis#111] opened 2019-11-19 02:03 UTC
https://paste.ubuntu.com/p/jQzhbgxZsK/

**Comment by Shadows-of-Fire** [comment] 2019-11-19 02:53
Duplicate of #108
(Will be fixed in next update, which should be today)

**Closed by Shadows-of-Fire** 2019-11-19 02:53 UTC
